name: CI - Development

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Gerar artefato
        run: zip -r app.zip . -x "node_modules/*" ".git/*"

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: app.zip

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: enterpise
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: enterprise

    steps:
      - name: Baixar artefato
        uses: actions/download-artifact@v4
        with:
          name: app-build

      - name: Extrair artefato
        run: unzip app.zip

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Criar tabela de teste
        run: |
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -u root -proot testdb -e "
          CREATE TABLE IF NOT EXISTS funcionarios (
            id INT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(255),
            role VARCHAR(255)
          );"

      - name: Rodar testes
        run: npm test

  quality:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Análise com SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=GabrielAlves106_pipeline-cicd-lint
            -Dsonar.organization=gabrielalves106
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  security:
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan de secrets com Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verificar vulnerabilidades (npm audit)
        run: npm audit --audit-level=high