name: CD - Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        run: npm ci

      - name: Build (opcional)
        run: echo "Build pronto"

      - name: Rodar migração (simulada)
        run: echo "Executando migrations..."

      - name: Deploy (simulado)
        run: echo "Deploy em produção realizado com sucesso"